export const Teensy_20 = [
  {
    type: "source_component",
    source_component_id: "generic_0",
    supplier_part_numbers: {},
  },
  {
    type: "schematic_component",
    schematic_component_id: "schematic_generic_component_0",
    source_component_id: "generic_0",
    center: {
      x: 0,
      y: 0,
    },
    rotation: 0,
    size: {
      width: 0,
      height: 0,
    },
  },
  {
    type: "pcb_component",
    source_component_id: "generic_0",
    pcb_component_id: "pcb_generic_component_0",
    layer: "top",
    center: {
      x: 0,
      y: 0,
    },
    rotation: 0,
    width: 29.692600000000002,
    height: 16.9926,
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_0",
    shape: "rect",
    x: -13.97,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["1"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_1",
    shape: "rect",
    x: -11.43,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["2"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_2",
    shape: "rect",
    x: -8.89,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["3"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_3",
    shape: "rect",
    x: -6.35,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["4"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_4",
    shape: "rect",
    x: -3.81,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["5"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_5",
    shape: "rect",
    x: -1.27,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["6"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_6",
    shape: "rect",
    x: 1.27,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["7"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_7",
    shape: "rect",
    x: 3.81,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["8"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_8",
    shape: "rect",
    x: 6.35,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["9"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_9",
    shape: "rect",
    x: 8.89,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["10"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_10",
    shape: "rect",
    x: 11.43,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["11"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_11",
    shape: "rect",
    x: 13.97,
    y: -7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["12"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_12",
    shape: "rect",
    x: 13.97,
    y: -5.08,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["13"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_13",
    shape: "rect",
    x: 13.97,
    y: -2.54,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["14"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_14",
    shape: "rect",
    x: 13.97,
    y: 0,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["15"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_15",
    shape: "rect",
    x: 13.97,
    y: 2.54,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["16"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_16",
    shape: "rect",
    x: 13.97,
    y: 5.08,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["17"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_17",
    shape: "rect",
    x: 13.97,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["18"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_18",
    shape: "rect",
    x: 11.43,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["19"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_19",
    shape: "rect",
    x: 8.89,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["20"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_20",
    shape: "rect",
    x: 6.35,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["21"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_21",
    shape: "rect",
    x: 3.81,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["22"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_22",
    shape: "rect",
    x: 1.27,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["23"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_23",
    shape: "rect",
    x: -1.27,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["24"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_24",
    shape: "rect",
    x: -3.81,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["25"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_25",
    shape: "rect",
    x: -6.35,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["26"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_26",
    shape: "rect",
    x: -8.89,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["27"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_27",
    shape: "rect",
    x: -11.43,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["28"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_28",
    shape: "rect",
    x: -13.97,
    y: 7.62,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["29"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_29",
    shape: "rect",
    x: -3.81,
    y: 5.08,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["30"],
  },
  {
    type: "pcb_smtpad",
    pcb_smtpad_id: "pcb_smtpad_30",
    shape: "rect",
    x: -3.81,
    y: -5.08,
    width: 1.7526,
    height: 1.7526,
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    port_hints: ["31"],
  },
  {
    type: "pcb_silkscreen_path",
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_0",
    route: [
      {
        x: -15.24,
        y: 8.89,
      },
      {
        x: -15.24,
        y: -8.89,
      },
    ],
    stroke_width: 0.1,
  },
  {
    type: "pcb_silkscreen_path",
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_1",
    route: [
      {
        x: -15.24,
        y: -8.89,
      },
      {
        x: 15.24,
        y: -8.89,
      },
    ],
    stroke_width: 0.1,
  },
  {
    type: "pcb_silkscreen_path",
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_2",
    route: [
      {
        x: 15.24,
        y: -8.89,
      },
      {
        x: 15.24,
        y: 8.89,
      },
    ],
    stroke_width: 0.1,
  },
  {
    type: "pcb_silkscreen_path",
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_3",
    route: [
      {
        x: 15.24,
        y: 8.89,
      },
      {
        x: -15.24,
        y: 8.89,
      },
    ],
    stroke_width: 0.1,
  },
  {
    type: "pcb_silkscreen_path",
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_4",
    route: [
      {
        x: -15.24,
        y: -6.35,
      },
      {
        x: -12.7,
        y: -6.35,
      },
    ],
    stroke_width: 0.1,
  },
  {
    type: "pcb_silkscreen_path",
    layer: "top",
    pcb_component_id: "pcb_generic_component_0",
    pcb_silkscreen_path_id: "pcb_silkscreen_path_5",
    route: [
      {
        x: -12.7,
        y: -6.35,
      },
      {
        x: -12.7,
        y: -8.89,
      },
    ],
    stroke_width: 0.1,
  },
  {
    type: "pcb_silkscreen_text",
    layer: "top",
    font: "tscircuit2024",
    font_size: 1.27,
    pcb_component_id: "pcb_generic_component_0",
    anchor_position: {
      x: 0,
      y: -1.625,
    },
    anchor_alignment: "center",
    text: "U1",
  },
  {
    type: "pcb_silkscreen_text",
    layer: "top",
    font: "tscircuit2024",
    font_size: 1.27,
    pcb_component_id: "pcb_generic_component_0",
    anchor_position: {
      x: 0,
      y: 0,
    },
    anchor_alignment: "center",
    text: "TEENSY2.0",
  },
]

export default Teensy_20
